import { csvToChart } from './csvToChart.js'
var varCsv = csvToChart.heredoc(config.data)
    csvToChart.createChartUseVar("chart", varCsv)
    csvToChart.initData("fileInput", "chart")
    csvToChart.configBtn("chart", "btn1")
    csvToChart.configBtn("chart", "btn2", "donut")
    csvToChart.configBtn("chart", "btn3", "spline")
    csvToChart.configBtn("chart", "btn4", "step")
    csvToChart.configBtn("chart", "btn5", "area")
    csvToChart.configBtn("chart", "btn6", "area-spline")
    csvToChart.configBtn("chart", "btn7", "bar")
    csvToChart.configBtn("chart", "btn8", "scatter")
    csvToChart.configBtn("chart", "btn9", "pie")
    csvToChart.configBtn("chart", "btn10", "gauge")
